### ISSUE TITLE
I ask  GPT to added a method for domain name resolution. It seems to be working normally, but I can’t be sure if there are any bugs. If you have time, could you please take a look?

### ISSUE THREAD

**Issue by hk1996yhx** [grpht/TCPClientPlugin#2]
int32 TCPClient::BeginConnect(const FString host, int32 port, std::function<void(FAsyncResultRef)> connectCallback, std::function<void(FAsyncResultRef)> disconnectCallback, std::any state)
{
	FIPv4Address ip;
	bool isValid = FIPv4Address::Parse(host, ip);
	if (!isValid)
	{ 
		ISocketSubsystem* SocketSubSystem = ISocketSubsystem::Get(PLATFORM_SOCKETSUBSYSTEM);
		TSharedRef<FInternetAddr> addr = SocketSubSystem->CreateInternetAddr(0, 0);
		ESocketErrors SocketError = SocketSubSystem->GetHostByName(TCHAR_TO_ANSI(*host), *addr);
		if (SocketError == SE_NO_ERROR)
		{
			addr->SetPort(port);
			isValid = FIPv4Address::Parse(addr->ToString(false), ip);
		}
	}
	if (!isValid)
	{
		return Connect_AddressisNotValid;
	}
	FIPv4Endpoint endpoint(ip, port);
	BeginConnect(endpoint, connectCallback, disconnectCallback, state);
	return 0;
}

**Comment by grpht** [comment]
I apologize for the late response. I am glad that you took an interest in this.
The ability to connect via domain has been added in the version 1.4 update.
Please check the UTCPClientSubsystem::GetDomainIpAddress method.

**Comment by grpht** [comment]
The issue has been resolved, so I will mark it as resolved.
